---
openapi: 3.0.2
info:
  title: API Pastry - 2.0
  version: 2.0.0
  description: API definition of API Pastry sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /pastry/{name}:
    summary: Specific operation on pastry
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pastry'
            examples:
              Eclair Cafe:
                value:
                  price: 2.6
          text/xml:
            schema:
              $ref: '#/components/schemas/Pastry'
            examples:
              Eclair Cafe Xml:
                value: "<pastry>\n\t<price>2.6</price>\n</pastry>"
        required: true
      parameters:
      - examples:
          Eclair Cafe:
            value: Eclair Cafe
          Eclair Cafe Xml:
            value: Eclair Cafe
        name: name
        description: pastry name
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pastry'
              examples:
                Eclair Cafe:
                  value:
                    name: Eclair Cafe
                    description: Delicieux Eclair au Cafe pas calorique du tout
                    size: M
                    price: 2.6
                    status: available
            text/xml:
              schema:
                $ref: '#/components/schemas/Pastry'
              examples:
                Eclair Cafe Xml:
                  value: |-
                    <pastry>
                        <name>Eclair Cafe</name>
                        <description>Delicieux Eclair au Cafe pas calorique du tout</description>
                        <size>M</size>
                        <price>2.6</price>
                        <status>available</status>
                    </pastry>
          description: Changed pastry
      operationId: PatchPastry
      summary: Patch existing pastry
    
    parameters:
    - name: name
      description: pastry name
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Pastry:
      title: Root Type for Pastry
      description: The root of the Pastry type's schema.
      type: object
      properties:
        name:
          description: Name of this pastry
          type: string
        description:
          description: A short description of this pastry
          type: string
        size:
          description: Size of pastry (S, M, L)
          type: string
        price:
          format: double
          description: Price (in USD) of this pastry
          type: number
        status:
          description: Status in stock (available, out_of_stock)
          type: string
      example:
        name: My Pastry
        description: A short description os my pastry
        size: M
        price: 4.5
        status: available
tags:
- name: pastry
  description: Pastry resource
