---
openapi: 3.0.2
info:
  title: API Pastry - 2.0
  version: 2.0.0
  description: API definition of API Pastry sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /API/GetNewCustomers:
    summary: Specific operation on customer
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
              examples:
                Eclair Cafe:
                  value:
                    DataSet:
                      Table:
                      - CustomerID: 12312313
                      - CustomerID: 12312314
                      - CustomerID: 12312315
                      - CustomerID: 12312316
                      - CustomerID: 12312317
                      - CustomerID: 12312318
                      - CustomerID: 12312319
                      - CustomerID: 12312310
                      - CustomerID: 12312311
                      - CustomerID: 12312312
                      - CustomerID: 12312112
          description: Changed pastry
      operationId: PatchPastry
      summary: Patch existing pastry
components:
  schemas:
    Customers:
      title: Root Type for custoemrs
      description: The root of the customers type's schema.
      type: object
      properties:
        DataSet:
          type: object
          properties:
            Table: 
              type: array
              items:
                type: object
                properties:
                  CustomerID:
                    type: string
      example:
        DataSet:
          Table: 
          - CustomerID: 12312313
          - CustomerID: 12312314
          - CustomerID: 12312315
          - CustomerID: 12312316
          - CustomerID: 12312317
          - CustomerID: 12312318
          - CustomerID: 12312319
          - CustomerID: 12312310
          - CustomerID: 12312311
          - CustomerID: 12312312
          - CustomerID: 12312112
          
tags:
- name: pastry
  description: Pastry resource
