---
openapi: 3.0.2
info:
  title: API Pastry - 2.0
  version: 2.0.0
  description: API definition of API Pastry sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /getCustomers:
    summary: Specific operation on customer
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
              examples:
                Eclair Cafe:
                  value:
                    DataSet:
                      name: achyuth
                    
          description: Changed pastry
      operationId: PatchPastry
      summary: Patch existing pastry
components:
  schemas:
    Customers:
      title: Root Type for custoemrs
      description: The root of the customers type's schema.
      type: object
      properties:
        DataSet:
          type: object
          properties:
            name: 
              type: string
      example:
        DataSet:
          name: nishnanath
tags:
- name: pastry
  description: Pastry resource
