---
openapi: 3.0.2
info:
  title: API Customers - 2.0
  version: 2.0.0
  description: API definition of API Customers sample app
  contact:
    name: Laurent Broudoux
    url: http://github.com/lbroudoux
    email: laurent.broudoux@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /API/GetNewCustomers:
    summary: Global operations on customers
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
            text/xml:
              schema:
                $ref: '#/components/schemas/Customers'
          description: Get list of customers
      operationId: GetCustomers
      summary: Get list of Customers
 
components:
  schemas:
    Pastry:
      title: Root Type for Pastry
      description: The root of the Pastry type's schema.
      type: object
      properties:
        name:
          description: Name of this pastry
          type: string
        description:
          description: A short description of this pastry
          type: string
        size:
          description: Size of pastry (S, M, L)
          type: string
        price:
          format: double
          description: Price (in USD) of this pastry
          type: number
        status:
          description: Status in stock (available, out_of_stock)
          type: string
      example:
        name: My Pastry
        description: A short description os my pastry
        size: M
        price: 4.5
        status: available
    Customers:
        type: object
        properties:
          name:
            type: string
          DataSet:
            type: object
            properties:
              Table:
                type: array
                items:
                  type: object
                  properties:
                    CustomerID:
                      type: string
                  
    PostBody:
      type: object
      properties:
        SinceDate:
          type: string
                
                
tags:
- name: customers
  description: customers resource
