---
openapi: 3.0.2
info:
  title: API Cargas - 1.0
  version: 1.0.0
  description: API definition of Cargas
  contact:
    name: Cargas-asdasdad
    url: https://asddasdasd
    email: achyuth@mailinator.com
paths:
  /API/GetNewCustomers:
    summary: Get list of new customers
    post:
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Customers'
              examples:
                New Customers Example:
                  value: '<Results>
  <DataSet>
    <Table>
      <CustomerID>136470</CustomerID>
    </Table>
    <Table>
      <CustomerID>136470</CustomerID>
    </Table>
  </DataSet>
</Results>'
                    
          description: Changed Customers
      operationId: GetNewCustomers
      summary: Get New Customers
  /API/GetCustomerAccount:
    summary: Get list of customer accounts
    post:
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/CustomerId'
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Accounts'
              examples:
                Customer Accounts Example:
                  value: '<Results>
  <DataSet>
    <Table>
      <CustomerID>136470</CustomerID>
      <CustomerStatus>Active</CustomerStatus>
      <CustomerType>Agriculture</CustomerType>
      <EmailAddress>achyuth@hotmail.com</EmailAddress>
      <Address1>136470 addresss</Address1>
      <Address2></Address2>
      <Address3></Address3>
      <City>bengaluru</City>
      <State>KA</State>
      <Zipcode>136479</Zipcode>
      <ContactPerson></ContactPerson>
      <PrimaryPhone>1364791456</PrimaryPhone>
      <CustomerLastName>manju136470</CustomerLastName>
      <CustomerFirstName>sarathi136470</CustomerFirstName>
    </Table>
  </DataSet>
</Results>'
                   
          description: Changed
      operationId: GetCustomerAccounts
      summary: Get Customer Accounts
  /API/GetCustomerLocations:
    summary: Get customer locations
    post:
      requestBody:
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/CustomerId'
      responses:
        "200":
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Locations'
              examples:
                Customer Locations Example:
                  value:
                    '<Results>
  <DataSet>
    <Table>
      <Name>136470</Name>
      <Address1>136470 address1</Address1>
      <Address2>123</Address2>
      <Address3></Address3>
      <City>city136479</City> 
      <State>state136479</State>
      <Zipcode>546546422</Zipcode>
     <ContactPerson>dasda22</ContactPerson>
      <Inactive>false</Inactive>
      <LocationType></LocationType>
      <PhoneNumber>(507) 227-4738</PhoneNumber>
    </Table>
    <Table>
      <Name>Primary Locationnnnnnnnnnnnnnn</Name>
      <Address1>500 INDIANA AVE22</Address1>
      <Address2></Address2>
      <Address3></Address3>
      <City>ADRIAN</City>
      <State>MN</State>
      <Zipcode>56110</Zipcode>
      <ContactPerson></ContactPerson>
      <Inactive>false</Inactive>
      <LocationType></LocationType>
      <PhoneNumber>(507) 227-4738</PhoneNumber>
    </Table>
   
  </DataSet>
</Results>'
          description: Changed
      operationId: GetCustomerLocations
      summary: Get Customer Locations
components:
  schemas:
    CustomerId:
      type: object
      properties:
        CustomerID:
          type: string
          description: Customer Id
          example: 12312313
    Customers:
      title: Root Type for custoemrs
      description: The root of the customers type's schema.
      type: object
      properties:
        Results:
          type: object
          properties:
            DataSet:
              type: object
              properties:
                Table: 
                  type: array
                  items:
                    type: object
                    properties:
                      CustomerID:
                        type: string

    Accounts:
      title: Root Type for accounts
      description: The root of the accounts type's schema.
      type: object
      properties:
        Results:
          type: object
          properties:
            DataSet:
              type: object
              properties:
                Table: 
                  type: array
                  items:
                    type: object
                    properties:
                      CustomerID:
                        type: string
                      CustomerStatus:
                        type: string
                      CustomerType:
                        type: string                  
                      EmailAddress:
                        type: string
                      Address1:
                        type: string                  
                      Address2:
                        type: string                  
                      Address3:
                        type: string                  
                      City:
                        type: string                  
                      State:
                        type: string                    
                      Zipcode:
                        type: string
                      ContactPerson:
                        type: string
                      PrimaryPhone:
                        type: string
                      CustomerLastName:
                        type: string
                      CustomerFirstName:
                        type: string
        
    Locations:
      title: Root Type for locations
      description: The root of the locations type's schema.
      type: object
      properties:
        Results:
          type: object
          properties: 
            DataSet:
              type: object
              properties:
                Table: 
                  type: array
                  items:
                    type: object
                    properties:
                      Name:
                        type: string
                      Address1:
                        type: string                  
                      Address2:
                        type: string                  
                      Address3:
                        type: string                  
                      City:
                        type: string                  
                      State:
                        type: string                    
                      Zipcode:
                        type: string
                      ContactPerson:
                        type: string
                      Inactive:
                        type: boolean
                      LocationType:
                        type: string                  
                      PhoneNumber:
                        type: string
   
